# Blog settings
permalink: /:title

# My variables
title: "PKoin"
author: 'Julien Fusco'
description: > # this means to ignore newlines until "baseurl:"
  Je m'appelle Julien Fusco. Je suis un artisan du web.
  Je fais des sites web et des applications mobiles.
  J'aime aussi faire un peu de devops.

# File management
exclude:
  - Gemfile
  - Gemfile.lock

# Markdown
markdown: kramdown

# More › http://kramdown.gettalong.org/quickref.html
# Options › http://kramdown.gettalong.org/options.html
kramdown:
  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    block:
      line_numbers: true
      start_line: 1
